# type (r;w;u;1-9),class,name,comment,QQ,ZZ,PBSB,ID,field1,part (m;s),type / templates,divider / values,unit,comment,field2,part (m;s),type / templates,divider / values,unit,comment,field3,part (m;s),type / templates,divider / values,unit,comment,field4,part (m;s),type / templates,divider / values,unit,comment,field5,part (m;s),type / templates,divider / values,unit,comment,field6,part (m;s),type / templates,divider / values,unit,comment,field7,part (m;s),type / templates,divider / values,unit,comment,field8,part (m;s),type / templates,divider / values,unit,comment
#,,Parameter Heizungsfachmann - Warmwasser,,,,,,,,,,,
*r,,,,,,"0902",,,,,,,
*w,,,,,,"0903",,,,,,,

r,,DHWMode,WW-Mode (361) ,,,,"350102",,,idhwmode,,,
w,,DHWMode, ,,,,"3501",,,idhwmode,,,
r,,MaxDHWTemp,Max-WW-Temp (362) ,,,,"340102",,,itemp10,,,
w,,MaxDHWTemp, ,,,,"3401",,,itemp10,,,
# Hier stimmt was nicht: Adresse prüfen,,,,,,,,,,,,,
r,,LegionnairesFunction,Legionellen-Funktion (363) ,,,,"010102",,,ilegionnairesday,,,
w,,LegionnairesFunction, ,,,,"0101",,,ilegionnairesday,,,
r,,TypeOfConstruction,Bauweise (371) ,,,,"280102",,,iconstructiontype,,,
w,,TypeOfConstruction, ,,,,"2801",,,iconstructiontype,,,
