# type (r;w;u;1-9),class,name,comment,QQ,ZZ,PBSB,ID,field1,part (m;s),type / templates,divider / values,unit,comment,field2,part (m;s),type / templates,divider / values,unit,comment,field3,part (m;s),type / templates,divider / values,unit,comment,field4,part (m;s),type / templates,divider / values,unit,comment,field5,part (m;s),type / templates,divider / values,unit,comment,field6,part (m;s),type / templates,divider / values,unit,comment,field7,part (m;s),type / templates,divider / values,unit,comment,field8,part (m;s),type / templates,divider / values,unit,comment
*r,,,,,,"5000",,,,,,,
r,,ProcessValues1,Prozesswerte ,,,,"0921201127112B0161",,s,_8_Skip,,, ,Byte1,s,UCH,,, ,Byte2,s,UCH,,, ,Byte3,s,UCH,,, ,Byte4,s,UCH,,, ,Byte5,s,UCH,,, ,Byte6,s,UCH,,, ,Byte7,s,UCH,,, ,Byte8,s,UCH,,,
r,,ProcessValues2,Prozesswerte ,,,,"BC1162016511700174",,s,_8_Skip,,, ,Byte1,s,UCH,,, ,Byte2,s,UCH,,, ,Byte3,s,UCH,,, ,FanControlSetSpeed,s,_8_Rpm60,,,Gebläseregelung Soll-Drehzahl ,FanControlActualSpeed,s,_8_Rpm60,,,Gebläseregelung Ist-Drehzahl ,Byte6,s,UCH,,,
r,,ProcessValues3,Prozesswerte ,,,,"B2017C01C40302",,s,_8_Skip,,, ,Byte1,s,UCH,,, ,Byte2,s,UCH,,, ,Byte3,s,UCH,,,
r,,ProcessValues4,Prozesswerte ,,,,"880122015B115F01660168",,s,_8_Skip,,, ,Byte1,s,UCH,,, ,Byte2,s,UCH,,, ,Byte3,s,UCH,,, ,Byte4,s,UCH,,, ,Byte5,s,UCH,,, ,Byte6,s,UCH,,,
r,,ProcessValues5,Prozesswerte ,,,,"1F016A116E118901B3",,s,_8_Skip,,, ,Byte1,s,UCH,,, ,Byte2,s,UCH,,, ,Byte3,s,UCH,,, ,Byte4,s,UCH,,, ,Byte5,s,UCH,,, ,Byte6,s,UCH,,,
r,,ProcessValues6,Prozesswerte ,,,,"603308",,s,_8_Skip,,, ,Byte1,s,UCH,,, ,Byte2,s,UCH,,, ,Byte3,s,UCH,,, ,Byte4,s,UCH,,,



