# type (r;w;u;1-9),class,name,comment,QQ,ZZ,PBSB,ID,field1,part (m;s),type / templates,divider / values,unit,comment,field2,part (m;s),type / templates,divider / values,unit,comment,field3,part (m;s),type / templates,divider / values,unit,comment,field4,part (m;s),type / templates,divider / values,unit,comment,field5,part (m;s),type / templates,divider / values,unit,comment,field6,part (m;s),type / templates,divider / values,unit,comment,field7,part (m;s),type / templates,divider / values,unit,comment,field8,part (m;s),type / templates,divider / values,unit,comment
# Parameter Endanwender - Urlaub,,,,,,,,,,,,,
*r,,,,,,"0902",,,,,,,
*w,,,,,,"0903",,,,,,,
#,,nur im HK1 vorhanden,,,,,,,,,,,
r,,StartOfHoliday,Urlaubsanfang (181) ,,,,"1B0104",Day,,_16_HolidayDay,,,Tag ,Month,,_16_HolidayMonth,,,Monat
# w,,StartOfHoliday, ,,,,"1B01",Day,,_16_HolidayDay,,, ,Month,,_16_HolidayMonth,,,
r,,StartOfHoliday.Day,Urlaubsanfang Tag (181) ,,,,"1B0102",,,_16_HolidayDay,,,
w,,StartOfHoliday.Day, ,,,,"1B01",,,_16_HolidayDay,,,
r,,StartOfHoliday.Month,Urlaubsanfang Monat (181) ,,,,"1C0102",,,_16_HolidayMonth,,,
w,,StartOfHoliday.Month, ,,,,"1C0102",,,_16_HolidayMonth,,,
r,,EndOfHoliday,Urlaubsende (182) ,,,,"1E0104",Day,,_16_HolidayDay,,,Tag ,Month,,_16_HolidayMonth,,,Monat
# w,,EndOfHoliday, ,,,,"1E01",Day,,_16_HolidayDay,,, ,Month,,_16_HolidayMonth,,,
r,,EndOfHoliday.Day,Urlaubsende Tag (182) ,,,,"1E0102",,,_16_HolidayDay,,,
w,,EndOfHoliday.Day, ,,,,"1E01",,,_16_HolidayDay,,,
r,,EndOfHoliday.Month,Urlaubsende Monat (182) ,,,,"1F0102",,,_16_HolidayMonth,,,
w,,EndOfHoliday.Month, ,,,,"1F01",,,_16_HolidayMonth,,,
r,,HolidayTemp,Urlaubstemperatur (183) ,,,,"2D0102",,,_16_TempReduced,,,
w,,HolidayTemp, ,,,,"2D0102",,,_16_TempReduced,,,
