# type (r;w;u;1-9),class,name,comment,QQ,ZZ,PBSB,ID,field1,part (m;s),type / templates,divider / values,unit,comment,field2,part (m;s),type / templates,divider / values,unit,comment,field3,part (m;s),type / templates,divider / values,unit,comment,field4,part (m;s),type / templates,divider / values,unit,comment,field5,part (m;s),type / templates,divider / values,unit,comment,field6,part (m;s),type / templates,divider / values,unit,comment,field7,part (m;s),type / templates,divider / values,unit,comment,field8,part (m;s),type / templates,divider / values,unit,comment
# Parameter Endanwender - Warmwasser,,,,,,,,,,,,,
*b,,,,,,"0902",,,,,,,
*r,,,,,,"0902",,,,,,,
*w,,,,,,"0903",,,,,,,

r;b,,DHWSetpoint,Warmwasser-Soll (176) ,,,,"130002",,,_16_Temp10,,,
w,,DHWSetpoint, ,,,,"1300",,,_16_Temp10,,,
r;b,,DHWMin,Warmwasser-Min (177) ,,,,"330102",,,_16_Temp10,,,
w,,DHWMin, ,,,,"3301",,,_16_Temp10,,,
