# type (r;w;u;1-9),class,name,comment,QQ,ZZ,PBSB,ID,field1,part (m;s),type / templates,divider / values,unit,comment,field2,part (m;s),type / templates,divider / values,unit,comment,field3,part (m;s),type / templates,divider / values,unit,comment,field4,part (m;s),type / templates,divider / values,unit,comment,field5,part (m;s),type / templates,divider / values,unit,comment,field6,part (m;s),type / templates,divider / values,unit,comment,field7,part (m;s),type / templates,divider / values,unit,comment,field8,part (m;s),type / templates,divider / values,unit,comment
# Parameter Endanwender - Urlaub,,,,,,,,,,,,,
*r,,,,,,"0902",,,,,,,
*w,,,,,,"0903",,,,,,,
#,,nur im HK1 vorhanden,,,,,,,,,,,
r,,StartOfHoliday,Urlaubsanfang (181) ,,,,"1B0104",Day,,iholidayday,,,Tag ,Month,,iholidaymonth,,,Monat
# w,,StartOfHoliday, ,,,,"1B01",Day,,iholidayday,,, ,Month,,iholidaymonth,,,
r,,StartOfHoliday.Day,Urlaubsanfang Tag (181) ,,,,"1B0102",,,iholidayday,,,
w,,StartOfHoliday.Day, ,,,,"1B01",,,iholidayday,,,
r,,StartOfHoliday.Month,Urlaubsanfang Monat (181) ,,,,"1C0102",,,iholidaymonth,,,
w,,StartOfHoliday.Month, ,,,,"1C0102",,,iholidaymonth,,,
r,,EndOfHoliday,Urlaubsende (182) ,,,,"1E0104",Day,,iholidayday,,,Tag ,Month,,iholidaymonth,,,Monat
# w,,EndOfHoliday, ,,,,"1E01",Day,,iholidayday,,, ,Month,,iholidaymonth,,,
r,,EndOfHoliday.Day,Urlaubsende Tag (182) ,,,,"1E0102",,,iholidayday,,,
w,,EndOfHoliday.Day, ,,,,"1E01",,,iholidayday,,,
r,,EndOfHoliday.Month,Urlaubsende Monat (182) ,,,,"1F0102",,,iholidaymonth,,,
w,,EndOfHoliday.Month, ,,,,"1F01",,,iholidaymonth,,,
r,,HolidayTemp,Urlaubstemperatur (183) ,,,,"2D0102",,,itempreduced,,,
w,,HolidayTemp, ,,,,"2D0102",,,itempreduced,,,
